/*
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.projection.ide.contentassist.antlr.internal.InternalCustomTerminalsParser;
import org.xtext.projection.services.CustomTerminalsGrammarAccess;

public class CustomTerminalsParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(CustomTerminalsGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, CustomTerminalsGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTerminalAccess().getAlternatives(), "rule__Terminal__Alternatives");
			builder.put(grammarAccess.getRuleAccess().getRulesAssignment(), "rule__Rule__RulesAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private CustomTerminalsGrammarAccess grammarAccess;

	@Override
	protected InternalCustomTerminalsParser createParser() {
		InternalCustomTerminalsParser result = new InternalCustomTerminalsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_LINE_COMMENT", "RULE_LINE_COMMENT2", "RULE_ALERT_LINE_COMMENT", "RULE_QUESTION_LINE_COMMENT", "RULE_GOOD_LINE_COMMENT", "RULE_REGION_COMMENT", "RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_WS" };
	}

	public CustomTerminalsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CustomTerminalsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
