/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.validation;

import org.xtext.projection.validation.AbstractCustomTerminalsValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CustomTerminalsValidator extends AbstractCustomTerminalsValidator {
}
