/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.scoping;

import org.xtext.projection.scoping.AbstractProjectionScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ProjectionScopeProvider extends AbstractProjectionScopeProvider {
}
