/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection;

import org.xtext.projection.CustomTerminalsStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CustomTerminalsStandaloneSetup extends CustomTerminalsStandaloneSetupGenerated {
  public static void doSetup() {
    new CustomTerminalsStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
