/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection;

import org.xtext.projection.ProjectionStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ProjectionStandaloneSetup extends ProjectionStandaloneSetupGenerated {
  public static void doSetup() {
    new ProjectionStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
