/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection;

import org.xtext.projection.AbstractProjectionRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ProjectionRuntimeModule extends AbstractProjectionRuntimeModule {
}
