/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.customTerminals;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.projection.customTerminals.CustomTerminalsPackage
 * @generated
 */
public interface CustomTerminalsFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CustomTerminalsFactory eINSTANCE = org.xtext.projection.customTerminals.impl.CustomTerminalsFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule</em>'.
   * @generated
   */
  Rule createRule();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CustomTerminalsPackage getCustomTerminalsPackage();

} //CustomTerminalsFactory
