/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.customTerminals;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.projection.customTerminals.Rule#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see org.xtext.projection.customTerminals.CustomTerminalsPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Rules</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rules</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' attribute list.
   * @see org.xtext.projection.customTerminals.CustomTerminalsPackage#getRule_Rules()
   * @model unique="false"
   * @generated
   */
  EList<String> getRules();

} // Rule
