/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.ide;

import org.xtext.projection.ide.AbstractCustomTerminalsIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CustomTerminalsIdeModule extends AbstractCustomTerminalsIdeModule {
}
