/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.ide;

import org.xtext.projection.ide.AbstractProjectionIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ProjectionIdeModule extends AbstractProjectionIdeModule {
}
