/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.projection;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.projection.projection.ProjectionPackage#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
} // Element
