/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.projection;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>My Decimal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.projection.projection.MyDecimal#getDec <em>Dec</em>}</li>
 * </ul>
 *
 * @see org.xtext.projection.projection.ProjectionPackage#getMyDecimal()
 * @model
 * @generated
 */
public interface MyDecimal extends Element
{
  /**
   * Returns the value of the '<em><b>Dec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dec</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dec</em>' attribute.
   * @see #setDec(String)
   * @see org.xtext.projection.projection.ProjectionPackage#getMyDecimal_Dec()
   * @model
   * @generated
   */
  String getDec();

  /**
   * Sets the value of the '{@link org.xtext.projection.projection.MyDecimal#getDec <em>Dec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dec</em>' attribute.
   * @see #getDec()
   * @generated
   */
  void setDec(String value);

} // MyDecimal
