/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.projection;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>My Int</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.projection.projection.MyInt#getInt <em>Int</em>}</li>
 * </ul>
 *
 * @see org.xtext.projection.projection.ProjectionPackage#getMyInt()
 * @model
 * @generated
 */
public interface MyInt extends Element
{
  /**
   * Returns the value of the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int</em>' attribute.
   * @see #setInt(int)
   * @see org.xtext.projection.projection.ProjectionPackage#getMyInt_Int()
   * @model
   * @generated
   */
  int getInt();

  /**
   * Sets the value of the '{@link org.xtext.projection.projection.MyInt#getInt <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int</em>' attribute.
   * @see #getInt()
   * @generated
   */
  void setInt(int value);

} // MyInt
