/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.projection;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>My Time</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.projection.projection.MyTime#getTime <em>Time</em>}</li>
 * </ul>
 *
 * @see org.xtext.projection.projection.ProjectionPackage#getMyTime()
 * @model
 * @generated
 */
public interface MyTime extends Element
{
  /**
   * Returns the value of the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Time</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' attribute.
   * @see #setTime(String)
   * @see org.xtext.projection.projection.ProjectionPackage#getMyTime_Time()
   * @model
   * @generated
   */
  String getTime();

  /**
   * Sets the value of the '{@link org.xtext.projection.projection.MyTime#getTime <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' attribute.
   * @see #getTime()
   * @generated
   */
  void setTime(String value);

} // MyTime
