/**
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.projection;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.projection.projection.ProjectionPackage
 * @generated
 */
public interface ProjectionFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ProjectionFactory eINSTANCE = org.xtext.projection.projection.impl.ProjectionFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  Element createElement();

  /**
   * Returns a new object of class '<em>My Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>My Text</em>'.
   * @generated
   */
  MyText createMyText();

  /**
   * Returns a new object of class '<em>My Int</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>My Int</em>'.
   * @generated
   */
  MyInt createMyInt();

  /**
   * Returns a new object of class '<em>My Decimal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>My Decimal</em>'.
   * @generated
   */
  MyDecimal createMyDecimal();

  /**
   * Returns a new object of class '<em>My Id</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>My Id</em>'.
   * @generated
   */
  MyId createMyId();

  /**
   * Returns a new object of class '<em>My Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>My Time</em>'.
   * @generated
   */
  MyTime createMyTime();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ProjectionPackage getProjectionPackage();

} //ProjectionFactory
