/*
 * generated by Xtext 2.15.0
 */
package org.xtext.projection


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ProjectionStandaloneSetup extends ProjectionStandaloneSetupGenerated {

	def static void doSetup() {
		new ProjectionStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
