/*
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.projection.parser.antlr.internal.InternalCustomTerminalsParser;
import org.xtext.projection.services.CustomTerminalsGrammarAccess;

public class CustomTerminalsParser extends AbstractAntlrParser {

	@Inject
	private CustomTerminalsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_LINE_COMMENT", "RULE_LINE_COMMENT2", "RULE_ALERT_LINE_COMMENT", "RULE_QUESTION_LINE_COMMENT", "RULE_GOOD_LINE_COMMENT", "RULE_REGION_COMMENT", "RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_WS");
	}
	

	@Override
	protected InternalCustomTerminalsParser createParser(XtextTokenStream stream) {
		return new InternalCustomTerminalsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Rule";
	}

	public CustomTerminalsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CustomTerminalsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
