/*
 * generated by Xtext 2.15.0
 */
package org.xtext.projection.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCustomTerminalsScopeProvider extends DelegatingScopeProvider {
}
